### ISSUE TITLE
Ban manual implementation of TryFuture and TryStream

### ISSUE THREAD

**Issue by taiki-e** [rust-lang-nursery/futures-rs#1776]
`Future<Output = Result<T, E>>` automatically implements `Tryfuture`. Also it can call `.await` and `FutureExt`'s methods without `TryFuture::into_future`.

Also, we may want to rewrite this trait to inherit `Future` in the future, so I think it makes sense to ban manual implementation for forward compatibility.
https://github.com/rust-lang-nursery/futures-rs/blob/78c5d852ec24edcf630a4c569c1234d078416f4f/futures-core/src/future/mod.rs#L61-L63

I'm thinking of using [the approach that `SliceIndex` uses](https://github.com/rust-lang/rust/blob/e1d7e4ae82c5500407e606c0b2b595597b9981f3/src/libcore/slice/mod.rs#L2621), but there may be better ways.

**Comment by taiki-e** [comment]
cc @cramertj @Nemo157

**Comment by Nemo157** [comment]
I think adding `Future` as a super trait combined with the existing `impl TryFuture for impl Future` would also accomplish this. Is there a reason to not have that supertrait bound now?

**Comment by taiki-e** [comment]
> Is there a reason to not have that supertrait bound now?

Nope, there is no particular reason. It's probably a better option.

**Comment by cramertj** [comment]
Yeah, @aturon and I hit a bug w/ cycles in the trait checker when attempting to do that:

```rust
trait Future { 
    type Output;
}

trait TryFuture: Future<Output = Result<Self::Ok, Self::Err>> {
    type Ok;
    type Err;
}
```
gives
```
error[E0391]: cycle detected when computing the supertraits of `TryFuture`
 --> src/main.rs:5:1
  |
5 | trait TryFuture: Future<Output = Result<Self::Ok, Self::Err>> {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which again requires computing the supertraits of `TryFuture`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> src/main.rs:5:1
  |
5 | trait TryFuture: Future<Output = Result<Self::Ok, Self::Err>> {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```
IIRC @nikomatsakis said this was fixed in chalk, but there's no ETA for the fix as far as I know.

**Comment by taiki-e** [comment]
Seems it can be avoided by using `<Self as TryFuture>::Ok`.
```rust
trait Future { 
    type Output;
}

trait TryFuture: Future<Output = Result<<Self as TryFuture>::Ok, <Self as TryFuture>::Err>> {
    type Ok;
    type Err;
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a9d4353ff24b3f2fa6a9c9281889dd86

**Comment by taiki-e** [comment]
Nope, this still doesn't work.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fad9b6f6899e6748118abec9fb199d26

**Comment by taiki-e** [comment]
So I believe #1777 is a good way at this time.
